spring:
  application:
    name: zyfz-achi
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non-null
  datasource:
    zyfz:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db1?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
      username: root
      password: root
    wlxy:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
      username: root
      password: root
    js_zyfz:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db2?characterEncoding=UTF-8&useOldAliasMetadataBehavior=true
      username: root
      password: root

server:
    port: 8088


#mybatis
mybatis:
  type-aliases-package: com.windmill
#  mapper-locations: classpath:/mapper/**/*.xml
  mapper-locations: classpath:/mapperMysql/**/*.xml

#mapper
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
#  identity: DB2
  identity: mysql

#pagehelper
pagehelper:
  helperDialect: mysql
#  helperDialect: db2
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    com.windmill: DEBUG #INFO DEBUG

db2OrMysql: mysql
#db2OrMysql: db2